spring:
  application:
    name: gateway-api
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8088}"
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_0