spring:
  application:
    name: route-service
  datasource:
    url: jdbc:postgresql://localhost:5432/route-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8088}"
springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_0
